### ASSIGNMENT  20-11-2023
#### 1. Learn the enumerate function.
#### 2. learn how to use the random.randit function in numpy.
#### 3. Learn how to reshape arrays.

In [1]:
# The enumerate fuction works thus:
floating_berries=["groundnut","cashew nut","burger"]
for items in enumerate (floating_berries):
    print(items)

(0, 'groundnut')
(1, 'cashew nut')
(2, 'burger')


In [3]:
#How to use random.randint:
import numpy as np
random_number=np.random.randint(1,10)
print(random_number)
random_array=np.random.randint(1,10,size=(3,3))
print(random_array)


3
[[7 5 1]
 [9 1 7]
 [5 4 1]]


In [5]:
#How to reshape arrays:
new_array=np.array([[4,5,6,],[2,1,3]]) 
#To reshappe this array to 3x2, it'll be:
reshape_array=new_array.reshape(3,2)
print("New_array=", new_array)
print("\nReshaped Array:", reshape_array)



New_array= [[4 5 6]
 [2 1 3]]

Reshaped Array: [[4 5]
 [6 2]
 [1 3]]
